name: Swift

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Code
      run: sh build.sh
    - name: Build Package
      run: swift build -v
    - name: Run tests
      run: swift test -v
